### ISSUE TITLE
version in setup.py is not aligned with git tags

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/gluster-integration#100]
Version specified in `setup.py` file is `0.0.1`, while the latest git tag (and releases page provided for these tags by github) is `v1.1`.

## Details

```
$ grep version setup.py
    version="0.0.1",
$ git tag
v1.0
v1.1
```

## Related Upstream Guidelines

https://packaging.python.org/distributing/#choosing-a-versioning-scheme
https://packaging.python.org/single_source_version/#single-sourcing-the-version

**Comment by TimothyAsirJeyasing** [comment]
@mbukatov , Now we are using https://github.com/Tendrl/gluster-integration/blob/master/version.py file to get the package version.
