### ISSUE TITLE
[rpm packaging] configuration files are not marked as configuration

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#103]
Package `tendrl-gluster-integration-0.0.1-1.el7.centos.noarch.rpm` from https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/ copr doesn't mark configuration files as configuration.

This breaks Fedora packaging policy and will have impact on user changes in
affected configuration files during package upgrades.
### Reproducer

```
# rpm -ql tendrl-gluster-integration | grep ^/etc
/etc/tendrl/gluster_integration
/etc/tendrl/gluster_integration_logging.yaml
# rpm -qc tendrl-gluster-integration | grep ^/etc
#
```

While expected result would be:

```
# rpm -ql tendrl-gluster-integration | grep ^/etc
/etc/tendrl/gluster_integration
/etc/tendrl/gluster_integration_logging.yaml
# rpm -qc tendrl-gluster-integration | grep ^/etc
/etc/tendrl/gluster_integration_logging.yaml
#
```

for more information see: https://github.com/Tendrl/commons/issues/72

**Comment by sankarshanmukhopadhyay** [comment]
@TimothyAsir @fbalak - is this issue present in latest builds?

**Comment by TimothyAsir** [comment]
This issue is not present in latest builds. Its resolved already.

**Comment by fbalak** [comment]
@TimothyAsir you are right. --> closing
