### ISSUE TITLE
service tendrl-gluster-integration missing config

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/gluster-integration#148]
Service tendrl-gluster-integration fails to start because it's configuration is missing.

journactl says
```
tendrl.commons.config.ConfigNotFound: Configuration for module: gluster-integration not found at /etc/tendrl/gluster-integration/gluster-integration.conf.yaml
```

When I list content of the `/etc/tendrl/gluster-integration` directory there's only `gluster-integration_logging.yaml` file.

Used packages:
tendrl-commons-1.2-02_23_2017_13_25_15.noarch
tendrl-node-agent-1.2-02_23_2017_15_56_11.noarch
tendrl-performance-monitoring-1.2-02_23_2017_12_14_51.noarch
tendrl-gluster-integration-1.2-02_23_2017_13_46_10.noarch

**Comment by r0h4n** [comment]
- You cannot start tendrl-{gluster, ceph}-integration standalone. The config file "gluster-integration.conf.yaml" is injected when a ImportCluster or CreateCluster tendrl API call is completed successfully 

I do not recommend, but you can try copying https://github.com/Tendrl/node-agent/blob/develop/etc/tendrl/node-agent/node-agent.conf.yaml.sample and making appropriate changes to try out the service

**Comment by ltrilety** [comment]
OK, thanks for information. The thing is that I cannot import cluster because of https://github.com/Tendrl/api/issues/82.
