### ISSUE TITLE
After the cluster import cluster_tendrl_context fields are not populated correctly 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#206]
After creating cluster, cluster_tendrl_context details in /clusters/<cluster_id>/TendrlContext are not getting populated correctly, except integration_id all other fields are empty. If we restart node-agent then all fields are getting populated.

**Comment by GowthamShanmugam** [comment]
@shtripat @nnDarshan @r0h4n

**Comment by r0h4n** [comment]
Fixed
