### ISSUE TITLE
Less nodes reported by gluster-integration in etcd

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/gluster-integration#226]
The number of nodes reported by gluster-integration under /clusters/cluster-id/nodes in etcd is less than actual number of nodes in gluster cluster.

I have a 3 node gluster-cluster but /clusters/cluster-id/nodes in etcd reports only 2

**Comment by anmolbabu** [comment]
Tried this second time and I am not able to reproduce this hence closing this for now...
Will reopen if this reoccurs...

**Comment by nnDarshan** [comment]
@anmolbabu Event I tried just now and could not reproduce
