### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#233]
According to https://github.com/Tendrl/gluster-integration/issues/133#issuecomment-288409086 there is no need for [installation.rst](https://github.com/Tendrl/gluster-integration/blob/master/doc/source/installation.rst). This file should be removed and [README.rst](https://github.com/Tendrl/gluster-integration/blob/master/README.rst) should contain information about that this component is installed from node-agent.

**Comment by r0h4n** [comment]
Thanks for filing the issue, Feel free to send a PR for the same

**Comment by fbalak** [comment]
Ok, I will do it. Opened same issue for ceph-integration: https://github.com/Tendrl/ceph-integration/issues/210
