### ISSUE TITLE
etcd does not preserve the order of bricks under the volume in etcd

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#236]
Gluster integration does not preserve the order of bricks while storing them under gluster volume in etcd. The order is very important as it gives information about the subvolumes (replica sets / etasure sub volume).

This has to be fixed. We should either maintain the order of bricks or have one more level under volumes for sub volumes(under this bricks will be stored).

**Comment by nnDarshan** [comment]
@shtripat @nthomas-redhat @r0h4n Please provide your inputs

**Comment by r0h4n** [comment]
Brick id's can be sequential keys in etcd instead of Brick uuid (uuid can be just an attribute of brick)

https://github.com/jplana/python-etcd/blob/0.4.5/src/etcd/client.py#L451

Search: "Atomically Creating In-Order Keys"
https://coreos.com/etcd/docs/latest/v2/api.html

**Comment by r0h4n** [comment]
@nnDarshan closing this one
