### ISSUE TITLE
Exceptions in gluster-integration

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/gluster-integration#245]
{u'bb0846e5-f9fa-4299-b9db-fb8c438973c4': {u'publisher': u'gluster_integration', u'job_id': u'', u'timestamp': u'2017-04-28 17:36:08.758784+00:00', u'caller': {u'function': u'_run', u'line_no': u'360', u'filename': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py'}, u'updated_at': u'2017-04-28 17:36:09.642893+00:00', u'payload': {u'exception_type': u'IndexError', u'message': u'error', u'exception_traceback': u'[{u\'function\': u\'run\', u\'line\': 327, u\'file\': u\'/usr/lib64/python2.7/site-packages/gevent/greenlet.py\', u\'statement\': u\'result = self._run(*self.args, **self.kwargs)\'}, {u\'function\': u\'_run\', u\'line\': 338, u\'file\': u\'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py\', u\'statement\': u"if out_lines[index].split(\'\\\\t\')[2].strip() != \'Connected\':"}]', u'exception': u'!!python/object/apply:exceptions.IndexError [list index out of range]\n'}, u'priority': u'error', u'parent_id': u'', u'node_id': u'9167cdb6-9891-43e9-b46d-9a1a5d4013de', u'cluster_id': u'', u'flow_id': u'', u'message_id': u'bb0846e5-f9fa-4299-b9db-fb8c438973c4'}}

**Comment by anmolbabu** [comment]
This is not very consistent and happens very rarely

**Comment by shtripat** [comment]
@anmolbabu just to confirm, in case of failures did you have any volumes in your setup? Also how many nodes are there in the trusted pool?

**Comment by anmolbabu** [comment]
@shtripat There were 3 nodes in the cluster/trusted pool but I am not very sure if I had any volumes I think I had 1 volume

**Comment by shtripat** [comment]
@anmolbabu I have tried with single node cluster, 4 node cluster, with volume and without volume scenarios and never saw the issue. Anyway looks like some corner case where `gstatus` is not returning the output in required formats.

Recently have seen bunch of issues raised against `gstatus`. Could be one of them but not very sure.

**Comment by anmolbabu** [comment]
@shtripat This was not very easily reproducible. I observed this after having my setup running for a long time. I think as you said it might be due to gstatus not reporting as expected after some cycles of execution but I feel it might help to add a conditional check on the o/p to match an expected format to prevent this failure... Please excuse me if I am wrong as I do not have the correct context of how/when this failure happens/ed

**Comment by shtripat** [comment]
@anmolbabu  for sure some check is required to make sure it doesnt crash with exception. Will do the required changes and push a PR.
