### ISSUE TITLE
Flow names should be consistent in definitions file.

### ISSUE THREAD

**Issue by anivargi** [Tendrl/gluster-integration#258]
https://github.com/Tendrl/gluster-integration/blob/develop/tendrl/gluster_integration/objects/definition/gluster.yaml currently defines all flows without the sds name like `CreateVolume` etc.. but there is a exception which defines a flow with sds name `CreateGlusterBrick`. 

One of the reasons to keep it consistent is the flow names are essentially used to generate API endpoints.
For ex: CreateVolume generates the API endpoint with the name /GlusterCreateVolume, but having names like CreateGlusterBrick will  generate the endpoint to be /GlusterCreateGlusterBrick.

So, to keep it consistent I am recommending we use CreateBrick as the flow name.

**Comment by r0h4n** [comment]
Fixed, closing
