### ISSUE TITLE
Gluster brick paths should be configurable

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#259]
* User should be able to configure the path under which bricks are created.
* Also in case of imported cluster tendrl should be able to figure the brick path by looking at the volumes
* Also  there should be way to specify brick path to tendrl, so that tendrl can figure out the user created free bricks located there
* tendrl should maintain a list of brick paths

**Comment by r0h4n** [comment]
This one's done right @nnDarshan
