### ISSUE TITLE
Change the structure of how gluster bricks gets stored in etcd

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#278]
Currently gluster bricks are stored under following 2 locations, `/cluster/<cluster-id>/nodes/<node-id>/GlusterBricks/` and `/cluster/<cluster-id>/volumes/<volume-id>/Bricks`. With this structure there will be difficulty to gather all the details about a given brick. So we have to move all the details under a single location and refer this from the other location.

## Details

We store all the attributes of bricks under `/cluster/<cluster-id>/GlusterBricks/` by modifying the current object structure of gluster bricks to include all attributes of Bricks object and it should also include field called `used` which says if the brick is used by any volume. A field to store the volume-id to which it belongs. also size of the brick(currently not there). The key for gluster bricks will be `<fqdn/ip>:<brick_path_with_underscores>`

GlusterBricks should have 3 sections `all`, `free` and `used`. Here `all` will have list of all bricks along with details. `free` and `used` will list only the key name of used and free brick respectively.

The current bricks object will be simplified to store only the keys of the bricks as all the other attributes will be stored under GlusterBricks. Also here there should be a restructure to depict the sub-volumes. The `Volumes/<vol-id>/Bricks/` path can have one more layer to indicate sub volume like `Volumes/<vol-id>/Bricks/subvolume<n>/`. That way API layer can easily figure out the bricks under a replica set.

Note: During gluster brick creation we create new gluster brick object with all the provisioning related details and the volume specific details will be blank(these are not used by any volumes yet). As part of sds sync thread we update the volume specific bricks details under GlusterBricks and then also update the key under `Volumes/vol-id/Bricks/sub-volume<n>/`

**Comment by nnDarshan** [comment]
@brainfunked @r0h4n @anivargi @shtripat @nthomas-redhat @cloudbehl Please have a look.

**Comment by r0h4n** [comment]
There seems to be some confusion, the new location for bricks will be` /clusters/:integration_id/Bricks/`  (with node_id as an attribute)

/volumes/:vol_id/Bricks/ will contain references to bricks objects saved in above location. Also,

**Comment by nnDarshan** [comment]
@r0h4n Thanks for pointing that out. I missed that, will edit it soon

**Comment by anivargi** [comment]
Can we make it consistent and always call it GlusterBricks or Bricks ?

**Comment by brainfunked** [comment]
* I agree with @anivargi. The naming convention needs to be a bit more consistent. I would probably prefer just Brick as the main brick object with all the brick details. The object for a brick participating in a volume needs a clear name that indicates that this object is for a brick in a volume.
* Would it not be easier to make a single object for a volume with all the brick references and subvolume information?

**Comment by nnDarshan** [comment]
@anivargi @brainfunked We need 2 different objects for bricks, one under clusters which has all the details, another under volume, and to differentiate these 2 objects we named it "GlusterBricks" and "Bricks". Brick info is updated only from the node where it is located unlike volume, so I feel its better to have separate object under volume for storing bricks.
And this brick object under volume can additionally have an attribute called subvolume-no: which can be used to map brick to subvolume instead of having one more level of subdirectory under bricks. 
Please provide your thoughts

**Comment by r0h4n** [comment]
@nnDarshan I had clearly pointed out 

> the new location for bricks will be /clusters/:integration_id/Bricks/ (with node_id as an attribute)
> 
> /volumes/:vol_id/Bricks/ will contain references to bricks objects saved in above location

Which means we can do with a single "Brick" class and let the volume/sub-volume simply have pointers to the Bricks 

The only place to store actual brick data should be `/clusters/:integration_id/Bricks/`

**Comment by brainfunked** [comment]
```@brainfunked If a Brick participates in a Volume, we simply add the vol_id to that Brick object, we do not need another Brick class for Bricks participating in a volume```

I agree. However, while this takes care of the linkage from the brick perspective, we do need to be able to readily see which bricks are participating in the volume, directly from the volume. What's your take on the way to implement this part @r0h4n @nnDarshan ?

**Comment by nnDarshan** [comment]
https://github.com/Tendrl/gluster-integration/issues/278#issuecomment-304814543
@brainfunked We will have reference `/volumes/:vol_id/Bricks/sub-volume<n>/<brick-name>` for that
Sounds okay ?

**Comment by r0h4n** [comment]
@brainfunked aha, yes, I missed writing that part down, ill summarize

- brick data should be /clusters/:integration_id/Bricks/
- /volumes/:vol_id/Bricks/sub-volume<n>/<brick-name>

**Comment by nnDarshan** [comment]
The fix patch has been merged
