### ISSUE TITLE
rebalance related details are saved incorrectly now

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#302]
Gluster get state provides the rebalance related information node wise i.e The rebalance related details provided by a get-state command is specific to that particular node. Its not general information like volume_name or volume_id.

But while storing we are not making any per node distinction and we are just saving it under volumes.

We should have one more layer under volume called rebalance_details where we can store the rebalance details per node.
Eg: 
**currently:**
 We have `/clusters/<cluster-id>/volumes/<volume-id>/rebalance.<attribute>` to which rebalance details of all nodes are saved. This is wrong as we are loosing per-node rebalance details

**Proposed:**
Have a directory under volumes called rebalance_details and under this store the details per-node
`/clusters/<cluster-id>/volumes/<volume-id>/reblance_details/<node-id>/rebalance.<attribute>`

**Comment by nnDarshan** [comment]
@shtripat @nthomas-redhat @anivargi @brainfunked @r0h4n Thoughts ?

**Comment by brainfunked** [comment]
The canonical way is always the storage system way. If we need to update the structure in etcd to faithfully reflect the state information provided by the storage system, we must, IMO.

**Comment by nnDarshan** [comment]
Also,this change would be needed to provide https://redhat.invisionapp.com/share/AB94BNET6#/screens/221686840 in UI
