### ISSUE TITLE
Dead Code

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/gluster-integration#316]
https://github.com/Tendrl/gluster-integration/blob/develop/tendrl/gluster_integration/manager/__init__.py#L96. I feel this is not needed unless someone manually runs manager/__init__.py.
I would like to submit a PR if this issue is legit
Also I would like to know where exactly the main() function is called.

**Comment by r0h4n** [comment]
https://stackoverflow.com/questions/419163/what-does-if-name-main-do

**Comment by rishubhjain** [comment]
@r0h4n Ya I am aware of its use, but I felt that since the modules are never explicitly called on a terminal they should not have if __name__ == "main", so is it needed or should I remove it?

**Comment by r0h4n** [comment]
Not really a big deal, we should keep it
