### ISSUE TITLE
Brick created on different path than provided

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#320]
When I try to create a gluster brick through the API call the brick is created on a different path than I specified.
I used this command:
```
curl -X POST -H 'Authorization: Bearer 24ace061648158f6925717ec488fcb02ae25a4ee18fdb9a7c4dfe8142d631fd5' -d '{"2c061dd2-0be4-487d-bcbf-053f791b6a76": {"/bricks/fs_gluster01": {"brick_name": "brick"}}, "8d1d2568-ee51-4f18-b856-0fef88bff28b": {"/bricks/fs_gluster01": {"brick_name": "brick"}}, "cd973131-7c3c-4a22-b096-3546264e641f": {"/bricks/fs_gluster01": {"brick_name": "brick"}}, "d9f7c454-9b82-4b45-939d-97fedc4baa02": {"/bricks/fs_gluster01": {"brick_name": "brick"}}}' http://hostname:9292/1.0/03419651-514b-4b65-a17e-2e169d3b1995/GlusterCreateBrick
```
And brick was created on path: `/tendrl_gluster_bricks/brick_mount/brick`

This behaviour should be documented or brick should be created on the provided path. (`/bricks/fs_gluster01/brick`)

**Comment by nnDarshan** [comment]
@fbalak This is the doc for creation of gluster brick through API : https://github.com/Tendrl/api/blob/master/docs/bricks.adoc#create-bricks

We don't support custom brick paths in tendrl (at least now). The API to create gluster brick does not take brick path anywhere, Its the device path(eg. /dev/vda) that you have to mention.

**Comment by fbalak** [comment]
@nnDarshan could you please add some comment to documentation that it only accepts device path and that bricks are created in directory `/tendrl_gluster_bricks/brick_mount`?

**Comment by nnDarshan** [comment]
@anivargi could you please make the doc change suggested at: https://github.com/Tendrl/gluster-integration/issues/320#issuecomment-311271987

**Comment by nnDarshan** [comment]
@anivargi can you please make the documentation change mentioned above, we can close this issue after that.

**Comment by r0h4n** [comment]
This issue is out of scope for now. Tendrl recommends using Gdeploy for Gluster operations.

**Comment by anivargi** [comment]
All the irrelevant doc for the current release has been removed from the API docs.
Ref: https://github.com/Tendrl/api/tree/master/docs
