### ISSUE TITLE
delete volume job passed for non existing volume

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/gluster-integration#325]
I've tried to delete volume which doesn't exist and job has passed. By passed I mean that job is marked by green sign. The state name is "finished". There is warning in job messages. I think this is wrong and job should be marked as failed with message that there is no volume which can be deleted. 

![delete_volume_bug](https://user-images.githubusercontent.com/5920442/27637408-e440c840-5c0f-11e7-8dbf-f6731c4f7d67.png)

**Comment by mbukatov** [comment]
@mkudlej could you add a package version?

**Comment by mkudlej** [comment]
Fixed with
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-gluster-integration-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-node-monitoring-1.4.2-1.el7.centos.noarch
