### ISSUE TITLE
bricks are not deleted after volume deleting

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/gluster-integration#332]
I think that bricks should be reusable after volume deleting so they should be deleted/wiped out for future usage.
Use-case example:
Gluster is used with small volumes for Samba users. If user lefts company his volumes are deleted. Bricks used in these deleted volumes should be wiped out to be able to reuse them for different users.

**Comment by r0h4n** [comment]
@mkudlej This seems like something Gdeploy should be doing and not Tendrl. 

Tendrl recommends using gdeploy for all Gluster operations.

@brainfunked please provide more thoughts

**Comment by r0h4n** [comment]
@brainfunked can you reply?
