### ISSUE TITLE
Gluster brick storage related detail sync is missing.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#333]
The gluster brick storage related details like the device used for the brick and size and the lvm related details (if valid) etc. should be synced as part of gluster sync.

This sync is needed as users might create bricks outside of tendrl

**Comment by nnDarshan** [comment]
@shtripat @r0h4n Do you feel we need a spec for this?

Am planning to use the [Blivet](https://github.com/storaged-project/blivet) package to get the device details under the brick.

**Comment by shtripat** [comment]
@nnDarshan I feel it would be good to have one as it might need some details/discussions around uses of blivet etc.

**Comment by brainfunked** [comment]
I think we need a spec to outline exactly how we'll be consuming blivet.

**Comment by brainfunked** [comment]
Also, how is this functionality placed in light of https://github.com/Tendrl/specifications/issues/167 ?

**Comment by nnDarshan** [comment]
@brainfunked This is actually one small enhancement that is part of https://github.com/Tendrl/specifications/issues/167
But as most of you suggested since this involves consuming an external library, will have a separate spec for this.

**Comment by brainfunked** [comment]
If the functionality belongs together, there's no harm in adding it to the same spec. Just add a separate section with details on blivet.
