### ISSUE TITLE
Use statvfs for brick mounts to figure out the brick utilization details

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#337]

**Comment by nnDarshan** [comment]
The current implementation of brick_utilization collection is using statvfs: https://github.com/Tendrl/gluster-integration/blob/develop/tendrl/gluster_integration/sds_sync/brick_utilization.py#L31

Feel this issue can be closed.

**Comment by shtripat** [comment]
Closing as confirmed by @nnDarshan
