### ISSUE TITLE
Calculate and populate no of hosts and volumes at cluster level

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#356]
While cluster data sync, calculate the total no of hosts and volumes and populate at cluster object level.

**Comment by gnehapk** [comment]
At volume level bricks and alerts count are needed. 
At host level alerts count is needed. Refer - https://github.com/Tendrl/specifications/pull/232/

**Comment by shtripat** [comment]
@gnehapk thanks for the details. Ack

**Comment by shtripat** [comment]
Added peer and volume count as part of https://github.com/Tendrl/gluster-integration/pull/352 at cluser level and it would be available under `clusters/{int-id}/GlobalDetails` as below

* `clusters/{int-id}/GlobalDetails/peer_count`
* `clusters/{int-id}/GlobalDetails/vol_count`

bricks count at volume is already available as `clusters/{int-id}/Volumes/{vol-id}/brick_count`

alerts count at volume and host level to be taken as apart of `monitoring-integration` based on alerts. @GowthamShanmugam @rishubhjain plz take care.

**Comment by shtripat** [comment]
This is kept open still as alert counts are still pending. @GowthamShanmugam plz close once alert counts done.

**Comment by GowthamShanmugam** [comment]
@shtripat sure

**Comment by nnDarshan** [comment]
@GowthamShanmugam Please update the issue, if alert count calculation is finished

**Comment by GowthamShanmugam** [comment]
@nnDarshan @shtripat this issue  is fixed we can close this

**Comment by shtripat** [comment]
Closing a s confirmed by @GowthamShanmugam
