### ISSUE TITLE
Removed entitites

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/gluster-integration#357]
Entities removed from gluster stay in tendrl and are shown in Graphite metrics and so in Grafana too.

Example of reproduction scenario:
1. Create new volume
2. Wait till the volume with proper bricks is present in Tendrl/Grafana
3. Remove the volume
4. Wait a while

Volume and its bricks remain in tendrl.
However bricks still "exist" on gluster machines no new data is collected.

**Comment by nnDarshan** [comment]
@rishubhjain @shtripat  Is this issue taken care of in the latest release ? If yes Pls update the issue

**Comment by shtripat** [comment]
@rishubhjain I feel with recent changes to update dashboard based on create/delete events from gluster for volumes/bricks, this should be taken care. Kindly confirm.

**Comment by rishubhjain** [comment]
@shtripat @nnDarshan The update dashboard is updating alert dashboard and not the normal dashboards, The issue I feel is regarding the normal dashboard, In my opinion this issue should not reappear but I am testing it to be sure. will update the issue once testing is done

**Comment by anmolbabu** [comment]
https://github.com/Tendrl/specifications/issues/249 captures some details related to this issue

**Comment by GowthamShanmugam** [comment]
When volumes is deleted volume details from grafana and graphite immediately, and from etcd volume, details are deleted by ttl.  

Issue is fixed, please verify

**Comment by ltrilety** [comment]
Checked on latest build.
