### ISSUE TITLE
Gluster version check should be changed to 3.12

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/gluster-integration#380]
Tendrl requires at least Gluster 3.12 but there is check during import for Gluster 3.9. This check should be changed to 3.12.

I've tried Tendrl with Gluster 3.10 and import has failed because Tendrl uses gluster command parameters which are not available in Gluster 3.10 and are available in Gluster 3.12.

**Comment by mbukatov** [comment]
Is there any official statement of supported GlusterFS versions? It would be nice to link it here before going on.

**Comment by atinmu** [comment]
Please note that the get-state support in glusterd was introduced in release-3.9 and further on what ever new enhancements were highlighted to core gluster have been addressed in release-3.12 branch. For active branch under maintenance we don't backport RFEs and hence certain enhancements will definitely not be available in release-3.10 branch.

Regarding the supported gluster version please refer https://www.gluster.org/community/release-schedule/

**Comment by shtripat** [comment]
@atinmu based on our discussion I understand, that once we bump the minimum required gluster version upstream as `3.12.0` still all the features downstream would be available as part of `3.8.4` dowstream.

Please ack this so that we can go ahead with the required changes.

**Comment by atinmu** [comment]
Thats correct

**Comment by shtripat** [comment]
@r0h4n in the light of confirmation from @atinmu the PR Tendrl/commons#713 suffices the required changes.

**Comment by shtripat** [comment]
@r0h4n this can be closed as required changes are merged

**Comment by shtripat** [comment]
This issue is verified at dev end but as per https://github.com/Tendrl/gluster-integration/issues/432 it might have to bumped to 3.12.2 once gluster is released.
@r0h4n in that case should we retain this PR and update later.

**Comment by nnDarshan** [comment]
@shtripat Since the Fix PR is merged. Should we close this. As we have #432 to track the latest minimum required version

**Comment by shtripat** [comment]
This one actually can be closed. @r0h4n plz do the needful.

**Comment by mkudlej** [comment]
Tested with 
```
etcd-3.2.5-1.el7.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.2-20170921T125939.61d8945.noarch
tendrl-api-httpd-1.5.2-20170921T125939.61d8945.noarch
tendrl-commons-1.5.2-20170921T220225.c77a8fc.noarch
tendrl-grafana-plugins-1.5.2-20170925T072405.6f3f855.noarch
tendrl-monitoring-integration-1.5.2-20170925T072405.6f3f855.noarch
tendrl-node-agent-1.5.2-20170922T094941.ced9876.noarch
tendrl-notifier-1.5.2-20170922T082559.b6a2768.noarch
tendrl-ui-1.5.2-20170921T165116.b85723e.noarch
```
and check is done for gluster 3.12
