### ISSUE TITLE
Invoke update dashboard flow from monitoring integration while addition of volume/brick/peer

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#385]
This should be done to update the dashboard immediately while adding a fresh volume / brick / peer while sds sync.

**Comment by nnDarshan** [comment]
@shtripat I guess we are waiting for gluster to provide brick related info as part of volume create event right. Once we have that, we can fully address this issue right ?

**Comment by shtripat** [comment]
Currently all the events taken care for peer/volume and brick for add/delete through events and update dashboard gets invoked. even while volume create, we find out the bricks and invoke the update dashboard as a workaround till the gluster event provides the bricks details as well as part of volume create event.

This ideally can be closed as changes are merged. I am closing this now and would create another when gluster event has brick details to accomodate the changes in gluster-integration.
