### ISSUE TITLE
Fix no rule to make target bzip-selinux-policy error during rpmbuild.

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/gluster-integration#421]
Add makefile to the source tar to get the selinux policy compilation during rpmbuild.
Currently tendrl-gluster-integration package and its sub packages are able to build locally.
However its failing in the automated build system due to missing target for compiling selinux policy.

Build Log:
make: * No rule to make target `bzip-selinux-policy'. Stop. make: * No rule to make target `bzip-selinux-policy'. Stop. RPM build errors: RPM build errors: error: Bad exit status from /var/tmp/rpm-tmp.vikKMR (%build) error: Bad exit status from /var/tmp/rpm-tmp.vikKMR (%build) Bad exit status from /var/tmp/rpm-tmp.vikKMR (%build) Bad exit status from /var/tmp/rpm-tmp.vikKMR (%build) Child return code was: 1 Child return code was: 1 EXCEPTION: [Error()] Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace result = func(*args, **kw) File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 590, in do raise exception.Error("Command failed:

**Comment by nthomas-redhat** [comment]
Closing this as this is already fixed
