### ISSUE TITLE
Update minimum required gluster version to 3.12.2 

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/gluster-integration#432]
There are certain fixes in glusterfs that would be needed for tendrl (get brick list as part of volume create event, get AFR subvol down events).  These fixes will be available in glusterfs 3.12.2

Tendrl should update its minimum required version of gluster to 3.12.2 when these fixes are available and when tendrl has made suitable changes(https://github.com/Tendrl/gluster-integration/issues/385) needed to handle them.

**Comment by nnDarshan** [comment]
@shtripat @r0h4n FYI

**Comment by shtripat** [comment]
@nnDarshan do you have a PR for this?

**Comment by nnDarshan** [comment]
>@nnDarshan do you have a PR for this?
@shtripat No, can you pls take care of this, when you would add code for consuming the brick list as part of volume create event(As its needed for adding dashboard)

**Comment by nnDarshan** [comment]
Keeping @atinmu in loop.
