### ISSUE TITLE
Set deleted flag while deletion of entities peer/volume/brick

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#439]
Set this flag while events for deletion of peer/volume/brick. This is required to make sure once deletion event raised for an entity, the deleted flag should be set and UI/api should not list these entities.

**Comment by rishubhjain** [comment]
@shtripat Should we do this for cluster as well?

**Comment by shtripat** [comment]
Cluster status is a calculated value already and valid values are `healthy` and `unhealthy`. This is already taken care I remember.

**Comment by shtripat** [comment]
Closing this as required PR are merged.
