### ISSUE TITLE
gluster integration sync failed with keyerror

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#445]
Oct 14 16:07:59 dhcp41-154 ansible-basic.py: Invoked with warn=True executable=None _uses_shell=True _raw_params=gluster pool list removes=None creates=None chdir=None
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: Exception in thread State sync thread:
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: Traceback (most recent call last):
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: self.run()
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: File "/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py", line 269, in run
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: raise ex
Oct 14 16:07:59 dhcp41-154 tendrl-gluster-integration: KeyError: 'total'

 Log meesage is pushed into node-agent socket but again exception is raised here(https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/sds_sync/__init__.py#L269) so sync thread is failed.

Oct 14 16:08:00 dhcp41-154 journal: 2017-10-14 10:37:59.947346+00:00 - gluster_integration - /usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py:265 - run - ERROR - gluster sds state sync error - KeyError: [{u'function': u'__bootstrap', u'line': 784, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.__bootstrap_inner()'}, {u'function': u'__bootstrap_inner', u'line': 811, u'file': u'/usr/lib64/python2.7/threading.py', u'statement': u'self.run()'}, {u'function': u'run', u'line': 232, u'file': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py', u'statement': u'utilization.sync_utilization_details(volumes)'}, {u'function': u'sync_utilization_details', u'line': 31, u'file': u'/usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/utilization.py', u'statement': u"raw_capacity += fetched_brick.utilization['total']"}]

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat

**Comment by GowthamShanmugam** [comment]
i saw this error only once, not sure it is reproducible

**Comment by shtripat** [comment]
@GowthamShanmugam I haven't faced this issue. Anyway I feel if the exception is sent to message socket, we can safely return without `ex` in the said line above.

@r0h4n ?

**Comment by r0h4n** [comment]
We should not ignore exception in sync cycle even if it is saved to central store

**Comment by GowthamShanmugam** [comment]
i feel it happened because of setup issue, shall we close this issue? we will re open when we see same issue

**Comment by GowthamShanmugam** [comment]
i am closing this issue because i am not seen this again, unable to reproduce
