### ISSUE TITLE
Use statfs() on mounted volume or gfapi for getting the volume utilization

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#446]
Currently uses a logic (lifted from gstatus) for calculation of volume utilization which is not a foolproof way of doing so. Also due to future changes or any internal changes within glusterfs would impact this logic in tendrl.

Rather, as suggested by glusterfs team, we should either be suing statfs() on mounted volume or gfapi call to get the volume utilization data.

**Comment by shtripat** [comment]
@nnDarshan @nthomas-redhat @Tendrl/tendrl-core

**Comment by shtripat** [comment]
Snippets from mail chain discussion with gluster team below


>> Yesterday while tendrl meeting, there was a concern raised by Martin Kudlej regarding mismatch >> between the volume utilization reported by tendrl and df command on underlying command.
>> The brick utilization data is returned by get-state command and we maintain in our central store.
>> The volume utilization data is aggregated based on a logic taken from gstatus in tendrl and 
>> updated to central store.
>> The volume utilization calculation logic in tendrl is present at [1]. Based on type of the volume,
>> the aggregation is done and updated.
>> Request you both to please check the logic and point out if any issues in our understanding and
>> if tendrl needs some changes for volume utilization calculation.

Reply from Atin
```Given Gluster is a distributed file system, it already offers the capability of the the brick details aggregation and offer the volume utilization capability by statfs() on the mount point of the volume. Individual brick's utilization can still be monitored through the get-state output or df on the brick. Having  such aggregation logic to be maintained for individual volume types is a pain and we should avoid that as much as possible. So tendrl just needs to send a statfs call (either through a temp mount or a gfapi call) for the volume.```

But @nthomas-redhat is of strong feeling that we should not mounting the volume and then getting the utilization details. Comments from @nthomas-redhat over gitter chat

```I don't think mounting volumes on provisioner node is the right way. All sorts of complications arise when nodes go down. Also asking admins to unmount before deleting is also is not user friendly. What I think is we need to push this to Gluster. Let Gluster provide us with right utilisation values at various levels.```
=========

**Comment by shtripat** [comment]
@mkudlej @Tendrl/tendrl-qe @atinmu @amarts ^^^

**Comment by mkudlej** [comment]
@Tendrl/tendrl-core So as I understand it, Tendrl will implement volume utilization (related and similar stats) via libgfapi and it will be done in next upstream release to avoid user confusion because of difference between ```df``` output on mounted volume and Tendrl UI. Did I get it right?

**Comment by atinmu** [comment]
We’re talking about temp (un)mount which needs to be handled inside the volume utilization code path and by the code. Please note that inside gluster codebase we do such mounts/unmounts in many places. One of the point which I didn’t understand from Nishanth’s statement is the complications around node down scenario. Can you clarify it @nthomas-redhat please?

**Comment by shtripat** [comment]
Based on our discussion within team the suggestion is -
```
While gluster-integration sync, on the aggregator node (currently known as provisioner node), create individual jobs for calculation of volume utilization for all the volumes in the cluster. These job would be picked by gluster nodes randomly and processed.

The job would use gfapi calls to calculate the utilization data on mounted volume. The mounting and un-mounting of volumes would be taken care internally by gfapi.
```

One concern we have seen earlier with job queue processor with huge no of jobs getting created while collectd configuration during import cluster flow. We might end up in the same situation here as well because every sync interval, no of volumes jobs would be created for utilization calculation. @r0h4n comments?

**Comment by nnDarshan** [comment]
> The job would use gfapi calls to calculate the utilization data on mounted volume. The mounting and un-mounting of volumes would be taken care internally by gfapi.
It would be better to have a python script which accepts a volume name and returns utilization. As part of the job we can run this script. Reason for suggesting to have it as a script is, gfapi has some minor memory leak issue. On long run it might cause issues if we have gfapi invocation as part of gluster-integration.

**Comment by nthomas-redhat** [comment]
> The job would use gfapi calls to calculate the utilization data on mounted volume. The mounting and un-mounting of volumes would be taken care internally by gfapi.
> It would be better to have a python script which accepts a volume name and returns utilization. As part of the job we can run this script. Reason for suggesting to have it as a script is, gfapi has some minor memory leak issue. On long run it might cause issues if we have gfapi invocation as part of gluster-integration.

This is good because tendrl need not worry about (un)mount of volumes during the calculations.
but @atinmu my worry is doing this for large number of volumes in every sync cycle. Does it have an impact on performance?

**Comment by amarts** [comment]
Impact is minimal because its just 1 call in few seconds. A gluster cluster can take 100k+ calls per second. One call per few second wouldn't cause any issue, even if there are 1000 volumes.

-Amar

**Comment by shtripat** [comment]
@amarts so what we are planning here is that volume-by-volume mount and then get the utilization data. Effectively its like no of volume calls per few seconds effectively in a cluster.

Also these mounting/unmounting we are planning to do in parallel from different nodes of the cluster (at least no of nodes volumes can be mounted simultaneously and utilization fetched). Hope this doesn't raise any concerns.

**Comment by shtripat** [comment]
Closing this as now gfapi is used for calculation of volume utilization. Its done from provisioner node volume by volume at the moment.
