### ISSUE TITLE
Issue in alert which comes under more than one classification

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#449]
The problem in current structure of alert is, The alerts are stored based on two classification
          1. cluster
          2. node

If the alert which related to cluster then we are storing the alert in two places:
             * /alerting/alerts
             * /alerting/clusters/{cid}

if the alert is related to the node then we are storing the alert in two places:
            * /alerting/alerts
            * /alerting/nodes/{nid}

and we are incrementing the alert count of the cluster alert count. We have to increment the alert count of volume also when an alert related to volume. 
problem 1:
            As per current structure we unable to find which alerts are related to volumes, there is no field in alerting object to specify that. We can add that alert type in tags but what we do when Brick_Down alert came? it is brick alert but also related to volume alert. And as per current structure, we can show the only count of volume. We can't show which alert is related to counting. UI is filtering alert using hostname. but the alert which is all related to cluster also has node name. This is not correct.  So here the summary of this problem is we can find alert count of volume related alert, because there is no field to specify this is volume alert. and Brick down alert is also a volume alert.

problem 2:
         Brick down alert are not only related to cluster it is related to:
                      * cluster
                      * node
                      * volume
     But current structure is storing as cluster alert only. and it is not considering it as volume alert also.

Solution:
------------
So we need to store the alert in hierarchy manner, what is my solution is:
     in classification field currently, we have two values either it is node or cluster. We change the classification like:
                 * [Node]
                 * [Cluster]
                  * [Node, Cluster]
These are the major classification of alert.

- When alert came node level it is stored in node level in etcd, and node alert count is incremented.
             * /alerting/alerts
             * /alerting/nodes/{nid}/alerts
- When alert came cluster level it is stored in cluster level in etcd, and cluster alert count is incremented.
              * /alerting/alerts
             * /alerting/cluster/{cid}/alerts
     Also if the alert is related to brick then give  alert_entity type as [Brick]
     if the alert is related to Volume then give  alert_entity type as [Volume]
     if  the alert is related to both volume and brick then give alert_entity type as [Brick, volume], so increment 
    alert brick down alert like this then it will increment volume alert count also. So etcd structure for cluster 
    alerts are:
             * /alerting/cluster/{cid}/alerts - all cluster alerts
             * /alerting/cluster/{cid}/volumes/{vid} - volume alerts 
            *  /alerting/cluster/{cid}/brick_alert/bircks/{bid} - brick alerts
            
- When alerts which related to node and cluster then we store in both:
              * /alerting/alerts
             * /alerting/cluster/{cid}/alerts
                 if related to vol:  then  /alerting/cluster/{cid}/volumes/{vid} 
                 if related to brick: then /alerting/cluster/{cid}/brick_alert/bircks/{bid}
                 or brick and volume store both
             * /alerting/nodes/{nid}/alerts
 Brick down alert will come in all the places. based on this count also incremented in node, cluster and volume also.

API can list the alert from /alerting/alerts/   it contain all alerts. the can fetch particular volume related alerts from /alerting/cluster/{cid}/volumes/{vid} easily.

1. Cluster alerts:
         * Peer status alert 
         * Svc  connected
         * Svc disconnected
         * Cluster utilization alert
         (these go only cluster alerts)
    1. Volume alerts:
           * Volume utilization alert
           * Volume status alert
           * Rebalance status alert 
           * Georeplication status alert 
           * Quorum of volume lost
           * Quorum of volume regained 
           * Minimum number of bricks not up in EC subvolume
           * Minimum number of bricks up in  EC subvolume
           * Afr quorum met for subvolume
           * Afr quorum fail for subvolume
           * Afr subvolume up          
           * Afr subvolume down
          (these go under cluster alerts + volume alerts)
   2. Brick alerts:
           * Brick status alerts (except brick down and up )
           * Brick utilization alert
          (these go only brick alert)
   3. All three:
          * Brick up and down
          (these will go under cluster+ volume + brick)

2. Node alerts:
      * Cpu utilization alert
      * Memory utilization alert
      * Swap utilization alert
    (these go only under node alerts)

3. All two:
      * Brick up and down
         (it will go node + cluster alerts (inside cluster alerts also it goes under  all category) )

   
Drawback
------------

This approach leads to lot of replication while storing alert obj. For brick down it is stored in all place so in 5 places it is replicated.

**Comment by GowthamShanmugam** [comment]
https://github.com/Tendrl/ui/issues/666

**Comment by GowthamShanmugam** [comment]
https://github.com/Tendrl/ui/issues/687

**Comment by GowthamShanmugam** [comment]
https://github.com/Tendrl/gluster-integration/issues/449

**Comment by GowthamShanmugam** [comment]
@Tendrl/tendrl-core Need your suggestion for this

**Comment by GowthamShanmugam** [comment]
Without changing structure we can increment the volume count using introducing a new variable 
entity_type as a list and we can place values like [brick, volume] for the brick down and other cluster alerts like we can give either [volume] or [brick] to increment the count.

and we can change change classification filed also like [node] or [cluster] or [node, cluster] to store the alert in node and cluster level or node or cluster.
that is also possible, Which is best approach @shtripat @r0h4n @anmolbabu @nnDarshan please comment on this.

**Comment by shtripat** [comment]
As we discussed this already in person, lets hear from others on this.

**Comment by GowthamShanmugam** [comment]
This issue is fixed, i am closing this
