### ISSUE TITLE
Maintain the alert dependencies in definition file and store the alert based on that relationships

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#452]
Alerts are stored in etcd based on two major categories called node or cluster, in earlier case alert will fall under any one this two catagory. The problem I that approach is some alerts may come under both of this category (e.g) brick connected or disconnected.  To solve this problem now node alert and cluster alert object has supported alert in definition file (https://github.com/Tendrl/commons/pull/766/files#diff-1a5320aa0fd1eea178e6ed255509c9c4R719) relationship section. so when the alert came then node-agent will compare the alert resource with the definition file and it will assign either the alert is node alert or cluster alert or both. So now classification field in the alert object is changed as list, when alert comes under both category then alert is stored 
   /alerting/alerts
  /alerting/cluster
  /alerting/nodes

node alert count and cluster alert count also increased based on this classification field.

here the question like how we can increment volume alert. So volume alert count object also have all supported alert in relationship section of the definition file (https://github.com/Tendrl/node-agent/pull/657/files#diff-49e81674b3e74da0b3896af7cc7df868R16). When alert came if alert classification has clustered in the list then alert send to volume alert check, the function will compare the alert with definition file then if it matches then it will increment the alert count for volume.

so when brick down alert came then classification field should be like ["node", "cluster"] so the alert stored under node and cluster alert as well as node and cluster alert count is incremented then it have "cluster" in classification list so it will also send to check volume alert count, if it matches then volume count also incremented.

**Comment by r0h4n** [comment]
Need more details

**Comment by GowthamShanmugam** [comment]
This issue is fixed i am closing this
