### ISSUE TITLE
georep session status changes

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#459]
Make the required changes to accomodate all possible georep session status values as below

CREATED: Geo-replication session is established
STOPPED: Geo-replication session is stopped
ONLINE/UP: Geo-replication session (All bricks) are UP and Running
OFFLINE/DOWN: Geo-replication session (All bricks) are Down
PARTIAL: Geo-replication session - some bricks are Online and Some bricks are offline
PAUSED: all the pairs are in paused state

**Comment by julienlim** [comment]
Ack the new 6 statuses for geo-repl sessions, and these should be reflected on the applicable Grafana dashboards. 

@shtripat

**Comment by julienlim** [comment]
Related to https://github.com/Tendrl/gluster-integration/pull/460

**Comment by shtripat** [comment]
Closing as required patches are merged
