### ISSUE TITLE
Two are more nodes are act as provisioner nodes

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#466]
When gluster-integration sync failed in one storage node or gluster-integration stops in any one node, then another node in gluster marked as provisioner node. When the gluster-integration started then both nodes act as provisioner node.It leads lot of problem while sync. (E.g) same alerts are raised from all provisioner nodes.

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat

**Comment by r0h4n** [comment]
How long was the original provisioner node down before you brought it back up?

**Comment by shtripat** [comment]
I also see two nodes marked as provisioner just after import.

**Comment by shtripat** [comment]
Fixed
