### ISSUE TITLE
Cluster's status shows "healthy", if the import failed for it.

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/gluster-integration#485]
I tried importing the cluster and it fails. But in the `/getClusterList` API, the status received for the cluster is "healthy"(globaldetails.status: "healthy").

**Comment by r0h4n** [comment]
If import of the cluster fails,  "globaldetails.status" should be a blank value. "globaldetails.status" is the health of the actual Gluster cluster (volume status, peer status etc), It has no connection to the import job failure. 

Once a cluster is successfully imported (i.e import_status=done, and is_managed=yes) only then `globaldetails.status` comes into existence.

**Comment by r0h4n** [comment]
Fixed tendrl-gluster-integration to not provide any Cluster health unless it is actually managed by Tendrl , please show value "unknown" or similar for health of unmanaged clusters

https://github.com/Tendrl/gluster-integration/commit/a0144767502ea837a5ff6572cb8cb5ac35ce18bd
