### ISSUE TITLE
Sometimes volume deleted flag is updated True to False again for deleted volumes

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#487]
After the execution of get-state command if the volume is deleted then the volume is updated as delete using gluster-event but sync will again update the volumes deleted flag as False. It will create a problem at monitoring-integration alert dashbaord sync. Problem is dashbaord is deleted when the volume is deleted, but while sync volume it will omit volume using deleted flag only, but in this case deleted flag is False for deleted volume so it creates a new panel for that volume and bricks while refreshing dashboard.

**Comment by GowthamShanmugam** [comment]
We can check the deleted flag while updating volume details from sync, the problem is many places in sync we are doing load_all for volumes, If volume is deleted after we done load_all then while saving the volume like volume_obj.save() will again update the volume deleted flag as False.

I feel we can create indexing for deleted volumes, when the volume is deleted we can create an entry like volume_id with deleted value True or false.  And we have to set the same ttl for particular volume index which corresponding volume obj have in etcd (because when volume object is deleted by ttl then index entry also deleted for that particular volume).  whenever we save or update volume details we have to check index volume using volume_id.

**Comment by GowthamShanmugam** [comment]
@r0h4n @nnDarshan @shtripat @nthomas-redhat suggestion please

**Comment by nnDarshan** [comment]
@GowthamShanmugam I feel indexing as you suggest would be a good idea. We need to make sure we update the indez onl from gluster_native_events handler. And *only read* the index whenever we want to check if a volume exists/not.
This also would reduce the size of info read from etcd during sync

**Comment by shtripat** [comment]
@GowthamShanmugam I am in favor of the indexing mechanism here.
I have a question though at this point. If we are removing the entries from dashboards immediately on event of volume delete, why not delete the entries from etcd as well at the same time. Retaining till TTL is causing confusions around?

@r0h4n comments?

**Comment by r0h4n** [comment]
If we delete objects when "delete" gluster native event is received, we need to ensure monitoring-integration has complete context (can be index) to be able to delete the related monitoring panels.

Apart from that the TTL and deleted flag arent of much use

**Comment by GowthamShanmugam** [comment]
This issue is fixed
