### ISSUE TITLE
Volume profile enabled/not-started info in tendrl

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#551]
If volume profiling is enabled for few volumes only and while import cluster in tendrl, the option `Enabled volume profiling` is not selected, the individual volumes should be marked as profiling enabled in tendrl UI. Also at cluster level it should be clearly marked that few volumes have profiling enabled.

**Comment by shtripat** [comment]
@r0h4n @nthomas-redhat @mbukatov @jjkabrown1 plz check and ack.

@julienlim I feel in the above scenario when profiling is enabled for few volumes and cluster is imported without selecting the option `Enable volume profiling`, after import we mark the cluster level value for `Profiling Enabled` as `partial` and at individual volume level we marked as `yes` for volume which have profiling enabled. What you suggest??

**Comment by julienlim** [comment]
Related bugs that can provide further background information:
* [Enable/Disable profiling doesn't work consistently #405](https://github.com/Tendrl/gluster-integration/issues/405)
* [BZ 'Disable' Volume Profiling during cluster import behavior](https://bugzilla.redhat.com/show_bug.cgi?id=1517215)

Here's a summary of what the problem and questions:
* Prior to a cluster import, the cluster has some number of volumes -- some of which have volume profiling turned on, and some that are not turned on.
* During the import, Tendrl needs to detect if cluster has a mixed of volume profiling configuration (enabled or disabled) for the various volumes in the cluster.  Moreover, in the Import Cluster (UI), we need a way to convey to the user that there is a "Partial" (indeterminate state) to the user, e.g.
![image](https://user-images.githubusercontent.com/5589919/35397201-da2ba160-01bc-11e8-818e-fcbb8ee5de75.png)
* Upon successful import execution, we need to indicate this indeterminate state in the "Volume Profiling" column (which currently shows "Enabled" or "Disabled") in the Cluster List.  Suggestions for the indeterminate state currently are "Partial," "Mixed," "Various."  Partial probably is not ideal as it may be too vague as is this partially enabled or partially disabled, and what does it exactly mean?

**Comment by mcarrano** [comment]
@julienlim I agree that "Mixed" makes the most sense. Furthermore, it the cluster is in a mixed state and the user takes an Enable Profiling or Disable Profiling action, I would expect this to change everything to the same (enabled or disabled) state.

**Comment by julienlim** [comment]
@shtripat @r0h4n @nthomas-redhat @mbukatov @jjkabrown1 @Tendrl/tendrl-core @gnehapk @a2batic @cloudbehl @Tendrl/tendrl-qe 

We've provided some UI guidance for handling the "partial" or "mixed" volume profiling scenario.

Will this be put into some kind of "Import Cluster" spec that will include the above considerations as well as what the changes we plan for the API as well?  Thanks.

**Comment by shtripat** [comment]
>> During the import, Tendrl needs to detect if cluster has a mixed of volume profiling configuration (enabled or disabled) for the various volumes in the cluster.

Ju, during import cluster flow, the tendrl-gluster-integration is not yet available not the storage nodes, and we dont have cluster information readily available. Once import gets over, the tendrl-gluster-integration runs get-state to figire out the volumes and their state information. Figuring out whether for some volumes profiling is enabled during import flow is not possible (we might end of running various gluster commands individually if we want to achieve this).

@r0h4n @nthomas-redhat comments?

**Comment by julienlim** [comment]
@shtripat Got it.  My thoughts is that we should provide 3 states to choose from during Import, i.e. enable/disable/leave existing volume profiling as-is -- to remove any ambiguity.  @mcarrano is putting together the update to the "Import Cluster" page in the UI.

@gnehapk @a2batic @cloudbehl @nthomas-redhat @r0h4n

**Comment by mcarrano** [comment]
I've updated the Import page to replace the "Enable volume profiling" checkbox with 3 radio buttons to expose the options as @julienlim lists above. You can find this design on InVision here: https://redhat.invisionapp.com/share/8QCOEVEY9#/247445416_Import_Clusters

**Comment by julienlim** [comment]
@shtripat @Tendrl/tendrl-core @gnehapk @a2batic @cloudbehl @nthomas-redhat @r0h4n @Tendrl/tendrl-qe @mcarrano Please note updated mockup from @mcarrano of Import Cluster to reflect the 3 states in radio buttons (vs. 2 state checkbox today), which should reduce user confusion and ambiguity.
