### ISSUE TITLE
Start/Stop volume profiling takes time in few cases

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#571]
As collectd plugins on the storage nodes run command like `gluster volume status` and `gluster volume heal` sometime running start/stop volume profiling back-to-back repeatedly might cause glusterd to end up into a locked state. With latest glusterfs release, this locks remains there for a time of ~6mins and released post that. By any change if a start/stop volume profiling flow fired from UI encounters this scenario, the flow might take approx 6 mins (or more) to complete as we wait for the task to be performed on the gluster level and then only report the job as completed.

**Comment by r0h4n** [comment]
Any updates?
