### ISSUE TITLE
Alerts are not generated when cluster/Volumes moves to un-healthy

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/gluster-integration#573]
1. Kill a brick or stop the volume
2. volume and cluster moves to warning state
3. Dashboard and UI reflects the states correctly
4. Alerts are not generated appropriately. But brick failure alerts are generated as expected

**Comment by nthomas-redhat** [comment]
I remember this was working the way I was explained above. Is there a change infunctionality or broken?

**Comment by shtripat** [comment]
With latest master rpms, I am able to see alerts while volume going down properly.
![screenshot from 2018-03-03 14-38-23](https://user-images.githubusercontent.com/6771252/36932571-a4af1a58-1ec2-11e8-9f8e-590a884eb803.png)
