### ISSUE TITLE
Unable to enable volume profiling

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#579]
I have a cluster with arbiter volume. I am unable to initiate `Volume profiling` from UI. I have tried to enable volume profiling during `cluster import` and in UI. The volume profiling still remains in `Disabled`. In events I see several messages `Value of volume profiling for volume: volume_beta_arbiter_2_plus_1x2 of cluster 6925ae1b-afdc-4bc3-97f0-90acf941fa1f changed from None to no` and in etcd /queue I see several jobs `tendrl.flows.ConfigureMonitoring` that have status `finished` and no error (I am not sure if this is relevant).

Tested with:
```
glusterfs-4.1dev-0.117.git2a1adc5.el7.centos.x86_64
tendrl-ansible-1.6.1-1.el7.centos.noarch
tendrl-api-1.6.1-1.el7.centos.noarch
tendrl-api-httpd-1.6.1-1.el7.centos.noarch
tendrl-commons-1.6.1-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.1-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.1-1.el7.centos.noarch
tendrl-node-agent-1.6.1-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.1-1.el7.centos.noarch
```

**Comment by shtripat** [comment]
Can you share the setup details in private message. Need to check once.

**Comment by fbalak** [comment]
@shtripat Sure, I sent you a message.

**Comment by r0h4n** [comment]
@shtripat any updates?
