### ISSUE TITLE
Gluster-integration fails with exception objects [VolumeOptions] not found in definitions

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#614]
VolumeObject is removed from definition file but it is not removed from objects directory, So gluster-integration is failed with an exception. So import cluster is not happening.

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat

**Comment by r0h4n** [comment]
@GowthamShanmugam please send a fix

@shtripat  I thought we had all moved objects covered

**Comment by shtripat** [comment]
https://github.com/Tendrl/gluster-integration/pull/617 fixes this as well.

**Comment by GowthamShanmugam** [comment]
This issue is fixed
