### ISSUE TITLE
Writing glusterd-state in /tmp should be changed

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#68]
While running tendrl-gluster-integration as service, its not able to read data written at /tmp/glusterd-state by glusterd service.
This happens because each service gets its own variation of /tmp and glusterd and tendrl-gluster-integration are two different services here in this case.
It could be set as /var/run/glusterd-state as its a runtime file.

**Comment by brainfunked** [comment]
`/var/lib/tendrl/<whatever>`.

**Comment by shtripat** [comment]
The path was changed
