### ISSUE TITLE
Volume status is not updating properly at etcd server when start and stop actions performed

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/gluster-integration#69]
Volume status is not updating properly at etcd server when start and stop actions performed.

**Comment by anmolsachan** [comment]
The issue is resolved now. Verification required with the stable release before closing.

**Comment by sankarshanmukhopadhyay** [comment]
It has being a while and a few builds tested since. Please confirm that this is indeed working and close this particular issue. @anmolsachan

**Comment by anmolsachan** [comment]
Volume status is now being updated properly, according to the latest master code. The issue can be closed now.
