### ISSUE TITLE
Delete the volume entry from etcd as well while volume delete

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#73]
Currently the volume is marked as deleted=True as an stop gap arrangement. Modify the same to delete the etcd entry post volume deletion flow.

**Comment by shtripat** [comment]
https://github.com/Tendrl/gluster_integration/pull/63

**Comment by r0h4n** [comment]
- Once we delete any object in etcd, we set its "deleted" flag as true. 
- @Tendrl/tendrl_api needs to respect this flag for list views for all objects

**Comment by shtripat** [comment]
@r0h4n so as part of my PR, if the record is permanently deleted from etcd the api listing GetVolumeList would not get the removed ones. So I dont see an issue as such.

**Comment by r0h4n** [comment]
@Tendrl/tendrl_api Please respond to above issue

**Comment by anivargi** [comment]
https://github.com/Tendrl/tendrl-api/issues/44

**Comment by sankarshanmukhopadhyay** [comment]
Is this and the referenced issue fixed?

**Comment by r0h4n** [comment]
This one is fixed. Tendrl now hard deletes volumes from its central store
