### ISSUE TITLE
Store configuration details in etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#81]
Instead of writing configuration details in file, store everything in etcd

**Comment by r0h4n** [comment]
Any updates/commits? Please reference them here

**Comment by GowthamShanmugam** [comment]
Specification: Tendrl/specifications#11

**Comment by shtripat** [comment]
This is done. Should be closed.

**Comment by GowthamShanmugam** [comment]
i am closing this issue
