### ISSUE TITLE
tendrl-gluster-integration can't be shipped with default configuration

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/gluster-integration#86]
It's not directly possible to ship `tendrl-gluster-integration` component with configuration file(s) which would contain all default values known in advance (eg. before installation).

Eg. we know that we need to set this piece of configuration into `/etc/tendrl/tendrl.conf` (see [installation.rst](https://github.com/Tendrl/gluster_integration/blob/master/doc/source/installation.rst)):

```
[gluster_integration]
log_cfg_path = /etc/tendrl/gluster_integration_logging.yaml
```

But it's not possible to ship this in a default configuration file in binary package, because `tendrl.conf` configuration file is owned by `tendrl-node-agent` component.

**Comment by mbukatov** [comment]
This issue may be related to https://github.com/Tendrl/gluster_integration/issues/81

**Comment by mbukatov** [comment]
I created issue for https://github.com/Tendrl/node_agent/issues/99 as well - since this component [happens to own](https://github.com/Tendrl/common/issues/74#issuecomment-265350087) the `tendrl.conf`.

**Comment by sankarshanmukhopadhyay** [comment]
@GowthamShanmugam @TimothyAsir please provide updates on this issue

**Comment by GowthamShanmugam** [comment]
@sankarshanmukhopadhyay @TimothyAsir i saw a code which is told by nisanth in import cluster, instead of shipping a configuration file they are generating at runtime.
