### ISSUE TITLE
[question] Does tendrl-gluster-integration require tendrl-node-agent?

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/gluster-integration#87]
Based on my understanding, tendrl-gluster-integration requires a tendrl-node-agent, but this is not directly mentioned in installation.rst file. Is my understanding correct (so that we need to add this into the docs)?

**Comment by shtripat** [comment]
tendrl-node-agent is the packae which is required on every storage node, be it gluster or ceph. Based on type of cluster maintained on the storage nodes, the specific tendrl-gluster-integration or tendrl-ceph-integration package is installed on storage node.

@mbukatov Hope this makes it clear..

**Comment by sankarshanmukhopadhyay** [comment]
The docs seem to have been updated. I am closing this issue. Please re-open if further conversation is required.
