### ISSUE TITLE
 Flows to get the cluster details

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/gluster-integration#92]
Currently to import a cluster, user expected to provide all the nodes in the cluster as input. This will be inconvenient if the size of the cluster is large. Instead the usecase flow is expected to be modified as:

select one of the node in cluster
use the selected node to get the details of the cluster
submit the request to all the nodes to import the cluster

This issue is to create a flow to get the cluster details

**Comment by r0h4n** [comment]
Link to spec issue?

**Comment by nthomas-redhat** [comment]
https://github.com/Tendrl/specifications/pull/60
